CREATE DATABASE Optus; 
GO

USE Optus;
GO

CREATE TABLE Usuario(
	IdUsuario INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Permissao BINARY,
	Senha VARCHAR(30) NOT NULL,
	Email VARCHAR(100) NOT NULL
);

CREATE TABLE Estilo(
	IdEstilo INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL
);

CREATE TABLE Artista(
	IdArtista INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(100)NOT NULL,

	IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo)
);

CREATE TABLE Album(
	IdAlbum INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	DataLancamento DATE,
	Localizacao VARCHAR(100),
	QtdMinutos INT,
	Ativo BINARY,

	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista)
);

CREATE TABLE EstiloAlbum(
	IdEstiloAlbum INT IDENTITY PRIMARY KEY NOT NULL,
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo)
);